version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      # - ./:/app  # Removed this line to use the JAR from the image
      - ~/.m2:/root/.m2
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ultra_accounting
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    command: >
      java -jar app.jar
    depends_on:
      - db
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static-data:/vol/static
    environment:
      - APP_HOST=app
      - APP_PORT=8080

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ultra_accounting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

volumes:
  static-data:
  postgres-data:
