name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-lint.yml
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
